Repository Team-Hanbae/Hanbae-Flutter, pull requests merged in 2025-04, with the labels that each got.

#14 [Feat] #13 홈스크린 그리기
  assets/images/AppBanner.png
  assets/images/banner/SurveyBanner.png
  lib/data/basic_jangdan_data.dart
  lib/data/custom_jangdan_data.dart
  lib/main.dart
  lib/presentation/home/home_screen.dart
Labels: enhancement

#16 [Feat] #15 컬러 등록
  lib/theme/colors.dart
Labels: enhancement

#18 [Feat] #17 컬러 파일 수정
  lib/theme/colors.dart
Labels: enhancement

#20 [Feat] #19 홈 스크린 컬러 넣기
  lib/main.dart
  lib/presentation/home/home_screen.dart
  lib/theme/colors.dart
Labels: enhancement

#21 [Feat] #12 MetronomeScreen 베이스
  lib/main.dart
  lib/model/accent.dart
  lib/model/jangdan.dart
  lib/presentation/metronome/hanbae_board.dart
  lib/presentation/metronome/metronome_control.dart
  lib/presentation/metronome/metronome_screen.dart
  lib/presentation/metronome/metronome_setting_control.dart
Labels: enhancement

#23 [Feat] #22 폰트 등록
  assets/fonts/Pretendard-Black.ttf
  assets/fonts/Pretendard-Bold.ttf
  assets/fonts/Pretendard-ExtraBold.ttf
  assets/fonts/Pretendard-ExtraLight.ttf
  assets/fonts/Pretendard-Light.ttf
  assets/fonts/Pretendard-Medium.ttf
  assets/fonts/Pretendard-Regular.ttf
  assets/fonts/Pretendard-SemiBold.ttf
  assets/fonts/Pretendard-Thin.ttf
  lib/presentation/home/home_screen.dart
  lib/theme/textStyles.dart
  pubspec.yaml
Labels: enhancement

#25 [Chore] #24 중간정리
  lib/main.dart
  lib/presentation/home/home_screen.dart
  lib/presentation/viewmodel/home_viewmodel.dart
  lib/presentation/viewmodel/metronome_viewmodel.dart
  lib/theme/text_styles.dart
  pubspec.yaml
Labels: chore

#26 [Feat] #9 MetronomeBloc 간단구현
  lib/bloc/metronome/metronome_bloc.dart
  lib/bloc/metronome/metronome_event.dart
  lib/bloc/metronome/metronome_state.dart
  lib/main.dart
  lib/model/jangdan.dart
  lib/presentation/metronome/hanbae_board.dart
  lib/presentation/metronome/metronome_screen.dart
Labels: enhancement

#38 [Feat] #37 BPM controler UI 디자인 적용
  lib/main.dart
  lib/presentation/metronome/metronome_control.dart
Labels: enhancement

#39 [Feat] #31 소박보기 구현
  lib/bloc/metronome/metronome_bloc.dart
  lib/bloc/metronome/metronome_event.dart
  lib/presentation/metronome/hanbae_board.dart
  lib/presentation/metronome/metronome_screen.dart
  lib/presentation/metronome/metronome_setting_control.dart
Labels: enhancement

#40 [Feat] #30 BPM 변경 기능
  lib/bloc/metronome/metronome_bloc.dart
  lib/presentation/metronome/metronome_control.dart
  lib/presentation/metronome/metronome_screen.dart
Labels: enhancement

#42 [Feat] #29 재생, 정지
  assets/sounds/beep_medium.mp3
  assets/sounds/beep_medium.wav
  assets/sounds/beep_strong.mp3
  assets/sounds/beep_strong.wav
  assets/sounds/beep_weak.mp3
  assets/sounds/beep_weak.wav
  assets/sounds/buk_medium.mp3
  assets/sounds/buk_medium.wav
  assets/sounds/buk_strong.mp3
  assets/sounds/buk_strong.wav
  assets/sounds/buk_weak.mp3
  assets/sounds/buk_weak.wav
  assets/sounds/jangu_medium.mp3
  assets/sounds/jangu_medium.wav
  assets/sounds/jangu_strong.mp3
  assets/sounds/jangu_strong.wav
  assets/sounds/jangu_weak.mp3
  assets/sounds/jangu_weak.wav
  lib/bloc/metronome/metronome_bloc.dart
  lib/bloc/metronome/metronome_event.dart
  lib/bloc/metronome/metronome_state.dart
  lib/data/sound_manager.dart
  lib/presentation/metronome/hanbae_board.dart
  lib/presentation/metronome/metronome_control.dart
  pubspec.yaml
Labels: enhancement

#43 [Feat] #41 UI 자잘하게 수정 및 실수 정정
  lib/main.dart
  lib/presentation/home/home_screen.dart
  lib/presentation/metronome/metronome_control.dart
  lib/presentation/metronome/metronome_screen.dart
  pubspec.yaml
Labels: enhancement

#45 [Feat] #44 홈화면에서 내가 저장한 장단 영역 삭제
  lib/presentation/home/home_screen.dart
  lib/theme/text_styles.dart
Labels: enhancement

#47 [Feat] #33 메트로놈 초기화
  lib/bloc/metronome/metronome_bloc.dart
  lib/bloc/metronome/metronome_event.dart
  lib/presentation/metronome/metronome_screen.dart
Labels: enhancement

#54 [Feat] #53 앱 아이콘
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  assets/images/icon/AppIcon.png
  pubspec.yaml
Labels: enhancement, chore

#52 [Feat] #51 엇모리 BakbarSet UI 변경
  lib/presentation/metronome/hanbae_board.dart
Labels: enhancement

#49 [Feat] #32 빠르기 찾기
  lib/bloc/metronome/metronome_bloc.dart
  lib/bloc/metronome/metronome_event.dart
  lib/bloc/metronome/metronome_state.dart
  lib/presentation/metronome/metronome_control.dart
Labels: enhancement

#55 [Feat] #50 BPM 연산 로직 변경
  lib/bloc/metronome/metronome_bloc.dart
Labels: enhancement

#56 [Feat] #48 Options UI 및 화면 깜빡임 기능 구현
  assets/images/icon/Icon_Flash.svg
  assets/images/icon/Icon_ListenSobak.svg
  assets/images/icon/Icon_SoundSwitch.svg
  assets/images/icon/Icon_ViewSobak.svg
  lib/bloc/metronome/metronome_bloc.dart
  lib/bloc/metronome/metronome_event.dart
  lib/bloc/metronome/metronome_state.dart
  lib/presentation/metronome/metronome_options.dart
  lib/presentation/metronome/metronome_screen.dart
  lib/presentation/metronome/metronome_setting_control.dart
  lib/theme/colors.dart
  pubspec.yaml
Labels: enhancement

#58 [Feat] #57 로딩화면
  android/app/src/main/res/values/styles.xml
  lib/presentation/metronome/metronome_screen.dart
  pubspec.yaml
Labels: enhancement, chore

#63 [Feat] #62 설문 배너 링크
  android/app/src/main/AndroidManifest.xml
  lib/presentation/home/home_screen.dart
  pubspec.yaml
Labels: enhancement

#64 [Feat] #59 메트로놈 화면 빠져나올때 정지
  lib/presentation/metronome/metronome_screen.dart
Labels: enhancement

#65 [Feat] #60 BPM 변경 LongTap
  lib/presentation/metronome/metronome_control.dart
Labels: enhancement

#69 [feat] #68 key 추가, 안드로이드 빌드 세팅
  .gitignore
  android/app/build.gradle.kts
  android/app/src/main/kotlin/com/example/hanbae/MainActivity.kt
  pubspec.yaml
Labels: release

#70 [Feat] #61 사운드 파일 교체
  assets/sounds/buk_medium.mp3
  assets/sounds/buk_strong.mp3
  assets/sounds/buk_weak.mp3
  assets/sounds/clave_medium.mp3
  assets/sounds/clave_strong.mp3
  assets/sounds/clave_weak.mp3
  assets/sounds/janggu_medium.mp3
  assets/sounds/janggu_strong.mp3
  assets/sounds/janggu_weak.mp3
  assets/sounds/jangu_medium.mp3
  assets/sounds/jangu_strong.mp3
  assets/sounds/jangu_weak.mp3
  lib/model/sound.dart
  lib/presentation/metronome/metronome_options.dart
  pubspec.yaml
Labels: enhancement

#71 [Release] #68 빌드 번호 업데이트
  pubspec.yaml
Labels: release

#74 [Feat] #73 배너 업데이트
  assets/images/banner/TestBanner.png
  lib/presentation/home/home_screen.dart
  pubspec.yaml
Labels: enhancement

#76 [Feat] #75 텍스트 크기 고정
  lib/main.dart
Labels: enhancement

#77 [Feat] #72 메트로놈스크린 UI 사이즈 수정
  lib/presentation/metronome/hanbae_board.dart
  lib/presentation/metronome/metronome_control.dart
  lib/presentation/metronome/metronome_options.dart
  lib/presentation/metronome/metronome_screen.dart
  lib/theme/text_styles.dart
Labels: enhancement

#80 [Feat] #78 사운드 재생 최적화
  android/app/src/main/kotlin/com/example/hanbae/MainActivity.kt
  android/app/src/main/kotlin/krabs/hanbae/MainActivity.kt
  android/app/src/main/res/raw/buk_medium.mp3
  android/app/src/main/res/raw/buk_strong.mp3
  android/app/src/main/res/raw/buk_weak.mp3
  android/app/src/main/res/raw/clave_medium.mp3
  android/app/src/main/res/raw/clave_strong.mp3
  android/app/src/main/res/raw/clave_weak.mp3
  android/app/src/main/res/raw/janggu_medium.mp3
  android/app/src/main/res/raw/janggu_strong.mp3
  android/app/src/main/res/raw/janggu_weak.mp3
  lib/bloc/metronome/metronome_bloc.dart
  lib/data/sound_manager.dart
  lib/main.dart
  pubspec.yaml
Labels: bug, enhancement

#83 [Fix] #82 사운드 안나는 이슈
  android/app/build.gradle.kts
  pubspec.yaml
Labels: bug

#85 [Feat] #84 메트로놈 스크린 UI 수선
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  assets/images/icon/AppIcon.png
  lib/presentation/home/home_screen.dart
  lib/presentation/metronome/hanbae_board.dart
  lib/presentation/metronome/metronome_control.dart
  lib/presentation/metronome/metronome_screen.dart
Labels: enhancement

#88 [Feat] #86 커스텀 장단
  lib/bloc/jangdan/jangdan_bloc.dart
  lib/bloc/jangdan/jangdan_event.dart
  lib/bloc/jangdan/jangdan_state.dart
  lib/bloc/metronome/metronome_bloc.dart
  lib/data/basic_jangdan_data.dart
  lib/data/jangdan_repository.dart
  lib/main.dart
  lib/model/accent.dart
  lib/model/accent.g.dart
  lib/model/jangdan.dart
  lib/model/jangdan.g.dart
  lib/model/jangdan_type.dart
  lib/model/jangdan_type.g.dart
  lib/presentation/custom_jangdan/custom_jangdan_create_screen.dart
  lib/presentation/custom_jangdan/custom_jangdan_list_screen.dart
  lib/presentation/home/custom_jangdan_list_screen.dart
  lib/presentation/home/home_screen.dart
  lib/presentation/metronome/metronome_screen.dart
  pubspec.yaml
Labels: enhancement

#90 [Feat] #89 디테일 수정
  lib/presentation/custom_jangdan/custom_jangdan_create_screen.dart
  lib/presentation/custom_jangdan/custom_jangdan_list_screen.dart
  lib/presentation/home/home_screen.dart
  lib/presentation/metronome/metronome_screen.dart
Labels: bug, enhancement

#93 [Feat] #91 ui 수정 및 음원 교체
  android/app/src/main/res/raw/buk_medium.mp3
  android/app/src/main/res/raw/buk_strong.mp3
  android/app/src/main/res/raw/buk_weak.mp3
  android/app/src/main/res/raw/clave_medium.mp3
  android/app/src/main/res/raw/clave_strong.mp3
  android/app/src/main/res/raw/clave_weak.mp3
  assets/sounds/buk_medium.mp3
  assets/sounds/buk_strong.mp3
  assets/sounds/buk_weak.mp3
  assets/sounds/clave_medium.mp3
  assets/sounds/clave_strong.mp3
  assets/sounds/clave_weak.mp3
  assets/sounds/janggu_medium.mp3
  assets/sounds/janggu_strong.mp3
  assets/sounds/janggu_weak.mp3
  lib/presentation/custom_jangdan/custom_jangdan_create_screen.dart
  lib/presentation/custom_jangdan/custom_jangdan_list_screen.dart
  lib/presentation/metronome/metronome_screen.dart
  lib/theme/text_styles.dart
Labels: enhancement

#96 [Fix] #95 BPM 변경사항이 커스텀 되도록
  lib/bloc/metronome/metronome_bloc.dart
  pubspec.yaml
Labels: bug

#100 [Feat] #99 소리 재생 최적화
  android/app/src/main/kotlin/krabs/hanbae/MainActivity.kt
  android/app/src/main/res/raw/buk_none.mp3
  android/app/src/main/res/raw/clave_none.mp3
  android/app/src/main/res/raw/janggu_none.mp3
  lib/bloc/metronome/metronome_bloc.dart
  lib/data/custom_jangdan_data.dart
  lib/main.dart
Labels: enhancement

#102 [Feat] #101 더미 사운드 재생
  android/app/src/main/kotlin/krabs/hanbae/MainActivity.kt
  lib/main.dart
Labels: enhancement

#104 [Feat] #103 사운드 간소화
  android/app/src/main/res/raw/buk_medium.mp3
  android/app/src/main/res/raw/buk_medium_.mp3
  android/app/src/main/res/raw/buk_strong.mp3
  android/app/src/main/res/raw/buk_strong_.mp3
  android/app/src/main/res/raw/buk_weak.mp3
  android/app/src/main/res/raw/buk_weak_.mp3
  android/app/src/main/res/raw/janggu_medium.mp3
  android/app/src/main/res/raw/janggu_medium_.mp3
  android/app/src/main/res/raw/janggu_strong.mp3
  android/app/src/main/res/raw/janggu_strong_.mp3
  android/app/src/main/res/raw/janggu_weak.mp3
  android/app/src/main/res/raw/janggu_weak_.mp3
Labels: enhancement

#108 [Release] #107 ver 0.3.0
  pubspec.yaml
Labels: release
